### ISSUE TITLE
adding public key

### ISSUE THREAD

**Issue by antton** [steevanb/ssh2bundle#1]
Hi, 

I try to use your bundle and I can connect into my ssh server and also create files inside and so on, but I can't echo my authorized_key with the exec command.

Any idea of how can I do it?

**Comment by steevanb** [comment]
Hi,

Could you please give me some code ?

**Comment by antton** [comment]
I get it working yesterday afternoon!
I needed to escape the public key before to exec on connection. Anyway thanks for your fast answer and really good work!
