### ISSUE TITLE
copying authorized_keys on /root/.ssh/ directory

### ISSUE THREAD

**Issue by antton** [steevanb/ssh2bundle#2]
Hi, 

I already have working when a user let his public key on the remote server authorized_keys file.

But as Debian and last Ubuntu versions as far as I know they don't let you authenticate with root user, I'd like to know if you see it possible to do with your library.

1.- Access remote server with user (Working)
2.- Send a command with sudo (sudo touch /root/.ssh/authorized_keys)
3.- Get the server answer ( (user) Password:)
4.- Send the sudo password 

I mean something like that. 

'''
<?php
    include('Net/SSH2.php');

```
$ssh = new Net_SSH2('www.domain.tld');
if (!$ssh->login('username', 'password')) {
    exit('Login Failed');
}

echo $ssh->read('username@username:~$');
$ssh->write("passwd\n");
echo $ssh->read('(current) UNIX password:');
$ssh->write("oldpassword\n");
echo $ssh->read('New UNIX password:');
$ssh->write("newpassword\n");
echo $ssh->read('Retype new UNIX password:');
$ssh->write("newpassword\n");
echo $ssh->read('passwd: all authentication tokens updated successfully.');
```

?>
'''

is not my code:
http://stackoverflow.com/questions/10116886/changing-password-of-unix-remote-server-through-php-ssh

Thanks!

**Comment by steevanb** [comment]
I don't think you can do that with SSH2 library, or i don't know how.

Sorry !
