### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by nicraMarcin** [steevanb/ssh2bundle#3]
Hi,
How to execute multiple commands?
i've have to make configuration on cisco device and in first command I've must execute "configure terminal" and next execute more commands.

```$connection->exec('conf t');
	    $conState = $connection->getState();
	    dump($conState);
	    $listing = $connection->exec('do show int status');
```

this throws error
```Warning: ssh2_exec(): Unable to request a channel from remote host```
dump shows that connection is established.

and there is no disconnect() method :/

**Comment by info-droid** [comment]
Did you tried `$connection->exec('configure terminal && do show int status');` ?

**Comment by steevanb** [comment]
Did you tried `$connection->exec('configure terminal && do show int status');` ?

**Comment by nicraMarcin** [comment]
Yes, I tried but without success 
```Line has invalid autocommand "conf t && do show int status"```
I also tired with semicolon but only first command was executed. 

With semicolon or double ampersand ssh2 works with linux hosts but not with cisco switches or routers :/

**Comment by steevanb** [comment]
Maybe `$connection->exec('first command');` then `$connection->exec('second command');` ?

I don't know how to do it, i just use SSH2 PHP extension in this bundle.

**Comment by nicraMarcin** [comment]
This desn't work.
With cisco I've to use phpseclib and emulate ssh terminal with write() and read()

**Comment by steevanb** [comment]
I'm sorry but i can't help you :(

**Comment by AdriwanKenoby** [comment]
Just separate your command with semicolon... Or use && for conditional execution
$connection->exec('command1 ; command2') will execute both command1 and command2.
$connection->exec('command1 && command2) will execute command2 only if command1 success.
